
#ifndef COMMTOOLS_VERSION_H
#define COMMTOOLS_VERSION_H
#include "VersionBase.h"
#include "CommToolsExportDef.h"
#define COMMTOOLS_VERSION_MAJOR  1
#define COMMTOOLS_VERSION_MINOR  0
#define COMMTOOLS_VERSION_MICRO  0

#define COMMTOOLS_VERSION_INT  VERSION_INT(COMMTOOLS_VERSION_MAJOR, \
	COMMTOOLS_VERSION_MINOR, \
	COMMTOOLS_VERSION_MICRO)
#define COMMTOOLS_VERSION      VERSION(COMMTOOLS_VERSION_MAJOR,    \
	COMMTOOLS_VERSION_MINOR,    \
	COMMTOOLS_VERSION_MICRO)
#define COMMTOOLS_BUILD        COMMTOOLS_VERSION_INT
COMM_TOOLS_API  const char* CommToolsVersionString();
COMM_TOOLS_API	int CommToolsVersionInt();
#endif