#ifndef ERROR_HELPER_H
#define ERROR_HELPER_H
#include <map>
#include <iostream>
#include "CommToolsExportDef.h"
#include "ly_util.h"
using namespace std;
using namespace G3P2P_BY_LONGYU;
using namespace G3P2P_BY_LONGYU::G3P2P_BY_LONGYU_UTIL;
//#include <atomic>
#ifdef WIN32
#pragma warning(disable:4251)
#endif
/*

*/
enum ERROR_CODE
{
	ERROR_CODE_SUCCEED = 0,								/*唯一成功码*/
	//ERROR_CODE_PAYLOAD_EMPTY = -16000000,				/*三层协议Payload为空*/
	//ERROR_CODE_UNKNOWN_ACTION = -16000001,				/*客户端操作Action类型错误*/
	//ERROR_CODE_OUT_OF_MEMORY = -16000002,				/*服务器内部申请内存出错*/
	//ERROR_CODE_CANNOT_CALL_CONFIG_SERVER= -16000003,	/*远端配置服务器不能访问*/
	//ERROR_CODE_CLIENT_IDENTITY_FAILED = -16000004,		/*用户认证信息验证失败*/
	//ERROR_CODE_CLIENT_TOKEN_ISNULL = -16000005,			/*用户认证Token为空*/
	//ERROR_CODE_CHECK_TOKEN_FAILED = -16000006,			/*用户Token检查失败*/
	//ERROR_CODE_CHECK_BIND_FAILED = -16000007,			/*用户邦定关系检查失败*/
	//ERROR_CODE_GET_ONLINEINFO_FAILED = -16000008,		/*查询在线信息错误*/
	//ERROR_CODE_PUSH_MSG_FAILED = -16000009,				/*推送消息失败*/
	//ERROR_CODE_PARMAS_EMPTY = -16000010,				//缺少参数
	//ERROR_CODE_GET_WHITE_LIST_FROM_DB_FAILED = -16000011,//缺少参数
	//ERROR_CODE_FIRST_PACKET_TYPE_NOT_AUTH = -16000012,	/*首个数据包，不是认证包*/
	//ERROR_CODE_HAS_NO_USABLE_FUNC_SERVER = -16000013,	/*没有可用的功能服务器*/
	//ERROR_CODE_MSG_FORWARD_FAILED = -16000014,			/*消息转发失败*/
	//ERROR_CODE_ACCOUNT_OFFSITE_LOGIN = -16000015,		/*账号异地登录*/
	//ERROR_CODE_ACCOUNT_OFFLINE = -16000016,              /*用户不在线*/
	ERROR_CODE_NETWORK_PACKET_LENGTH_TOO_LONG = -101000,	    /*数据包总长度大于缓冲区最大长度*/
	ERROR_CODE_NETWORK_EXTEND_ZERO,								/*第二层协议的扩展区为零*/
	ERROR_CODE_NETWORK_NONE_USER_DATA,							/*第二层协议的用户数据不存在*/
	ERROR_CODE_NETWORK_CHECKSUM_FAILED,							/*数据包校验失败*/
	ERROR_CODE_NETWORK_PROTOCOL_FLAG_ERROR,						/*协议标记错误*/
	ERROR_CODE_NETWORK_NONE_SOCKET_HANDLE,						/*Socket句柄不存在*/
	ERROR_CODE_BUSINESS_COMMON_ERROR_PARAMETER = -110000,		/*参数错误*/
	ERROR_CODE_BUSINESS_COMMON_EMPTY_PARAMETER,					/*参数为空*/
	ERROR_CODE_BUSINESS_COMMON_CANNOT_ACCESS_ROMOTE_SERVER,		//无法访问远端服务器
	ERROR_CODE_BUSINESS_COMMON_OUT_OF_MEMORY,					/*申请内存失败*/
	ERROR_CODE_BUSINESS_COMMON_PAYLOAD_EMPTY,					/*三层协议Payload为空*/
	ERROR_CODE_BUSINESS_COMMON_ERROR_REQUEST_ACTION,			/*请求类型错误*/
	ERROR_CODE_BUSINESS_COMMON_PUSH_MSG_FAILED,					/*推送消息失败*/
	ERROR_CODE_BUSINESS_COMMON_NULL_POINTER,					/*指针为空*/
	ERROR_CODE_CONFIG_SERVER_NO_AVAILABLE_DATA = -111000,		/*无可用的数据*/
	ERROR_CODE_CONFIG_SERVER_CANNOT_GET_DATA ,					/*无法获取数据*/
	ERROR_CODE_CONFIG_SERVER_REGISTER_FAILED,					/*向配置服务器注册失败*/
	ERROR_CODE_AUTH_SERVER_CLIENT_IDENTITY_FAILED = -114000,	/*客户端认证信息验证失败*/
	ERROR_CODE_AUTH_SERVER_CLIENT_TOKEN_IS_NULL,				/*用户认证Token为空*/
	ERROR_CODE_AUTH_SERVER_CHECK_TOKEN_FAILED ,					/*用户Token检查失败*/
	ERROR_CODE_USER_NOT_ONLINE,									/*用户还未上线*/
	ERROR_CODE_USER_ALREADY_ONLINE,								/*用户已经上线*/
	ERROR_CODE_AUTH_SERVER_REMOTE_INVOKE_FAILED,				/*远端内部服务器调用失败*/
	ERROR_CODE_AUTH_USER_NAME_OR_PASSWD_INCORRECT,				/*登录用户名或密码错误*/
	ERROR_CODE_AUTH_USER_CAPTCHAT_INCORRECT,					/*验证码错误*/
	ERROR_CODE_AUTH_USER_CAPTCHAT_EXPIRE,						/*验证码过期*/
	ERROR_CODE_MSG_SERVER_FIRST_PACKET_TYPE_NOT_AUTH = -115000,	/*首个数据包，不是认证包*/
	ERROR_CODE_MSG_SERVER_ACCOUNT_OFFSITE_LOGIN,				/*账号异地登录*/
	ERROR_CODE_MSG_SERVER_MSG_FORWARD_FAILED ,					/*消息转发失败*/
	ERROR_CODE_ONLINE_SERVER_QUERY_DATA_FAILED = -116000,		/*查询数据失败*/
	ERROR_CODE_ONLINE_SERVER_UPDATE_DATA_FAILED ,				/*更新数据失败*/
	ERROR_CODE_ONLINE_SERVER_DELETE_DATA_FAILED ,				/*删除数据失败*/
	ERROR_CODE_ONLINE_SERVER_ADD_DATA_FAILED ,					/*添加数据失败*/
	ERROR_CODE_INESAHOME_SERVER_CHECK_BIND_FAILED = -117000,	/*用户邦定关系检查失败*/
	ERROR_CODE_INESAHOME_SERVER_DEVICE_ILLEGAL_EQUIPMENT,		/*非法的设备*/
	ERROR_CODE_INESAHOME_SERVER_GET_ONLINEINFO_FAILED,			/*查询在线信息错误*/
	ERROR_CODE_INESAHOME_SERVER_ACCOUNT_OFFLINE,				/*用户不在线*/
	ERROR_CODE_INESAHOME_SERVER_SAVE_ONEKEYWARNINGMSG_FAILED,	/*保存一键报警信息失败*/
	ERROR_CODE_INESAHOME_SERVER_GET_WHITE_LIST_FROM_DB_FAILED,	/*获取白名单列表失败*/
	ERROR_CODE_INESAHOME_SERVER_ADD_WHITE_LIST_TO_DB_FAILED,    /*添加白名单列表失败*/
	ERROR_CODE_INESAHOME_SERVER_SAVE_STRATEGY_FAILED,           /*保存策略失败*/
	ERROR_CODE_INESAHOME_SERVER_DEL_STRATEGY_FAILED,            /*删除策略失败*/
	ERROR_CODE_INESAHOME_SERVER_ENABLE_STRTATEGY_FAILED,        /*使能策略失败*/
	ERROR_CODE_INESAHOME_SERVER_OPT_CANNOT_SUPPORT,				/*操作不支持*/
	ERROR_CODE_DATA_STORAGE_SERVER_SQL_CMD_EMPTY = -118000,		/*sql命令语句为空*/
	ERROR_CODE_DATA_STORAGE_SERVER_REQDATA_TOO_MUCH,			/*用户请求数据太大*/	
	ERROR_CODE_DATA_STORAGE_DATA_CACHE_FAILED,					/*数据缓存失败*/
	ERROR_CODE_DATAPROXY_REQ_PATH_ERROR =  -119000,				/*请求路径错误*/

};

class COMM_TOOLS_API ErrorHelper
{
public:
	ErrorHelper(void);
	~ErrorHelper(void);
public:
	static const char* GetErrorMessage(const int errnum);
	static void InitErrorMessage();
private:
	static std::map<int,std::string> m_ErrDescribe;
	//static std::atomic_bool m_isInit;
	static bool m_isInit;
	static CCommonMutex m_ErrMsgMutex;
	
};

#endif