#ifndef PAPEREADER_VERSION_H
#define PAPEREADER_VERSION_H
#include "VersionBase.h"

#define PAPEREADER_VERSION_MAJOR  1
#define PAPEREADER_VERSION_MINOR  0
#define PAPEREADER_VERSION_MICRO  0

#define PAPEREADER_VERSION_INT  VERSION_INT(PAPEREADER_VERSION_MAJOR, \
	PAPEREADER_VERSION_MINOR, \
	PAPEREADER_VERSION_MICRO)

#define PAPEREADER_VERSION VERSION(PAPEREADER_VERSION_MAJOR,    \
	PAPEREADER_VERSION_MINOR,    \
	PAPEREADER_VERSION_MICRO)

#define PAPEREADER_BUILD PAPEREADER_VERSION_INT

extern "C" const char* PapereaderVersionString();
extern "C" int PapereaderVersionInt();

#endif